import type { WalkerProfile } from '@/entities/walker/model/types';

export const walkerMock: WalkerProfile = {
  id: 'walker_001',
  name: 'Ethan Brooks',
  avatar: 'https://example.com/avatar.jpg',
  status: 'on_walk',
  headline: 'Certified Pet Care Professional',
  experienceYears: 6,
  location: 'Downtown Seattle',
  rating: {
    average: 4.9,
    reviewsCount: 287,
  },
  stats: {
    servicesDone: 1240,
    repeatClientsPercent: 83,
    onTimePercent: 99.2,
    avgWalkMinutes: 47,
    responseTime: '< 5 min',
    companies: 3,
  },
  badges: ['ID Verified', 'Background Checked', 'Insured', 'Pet First Aid', 'Top Rated', 'Multi-Dog'],
  lastActivity: {
    timeAgo: '12 min ago',
    description: 'Completed walk in Williamsburg',
  },
  pricing: {
    walking30min: 28,
    walking60min: 44,
    petSitting: 35,
    homeVisit: 28,
    grooming: 45,
    extraPet: 10,
    currency: 'USD',
  },
  ratingsBreakdown: {
    reliability: 4.9,
    punctuality: 5,
    communication: 4.8,
    safety: 5,
    petCare: 4.9,
  },
  serviceArea: {
    radiusMiles: 5,
    areas: ['Downtown', 'Capitol Hill', 'Queen Anne'],
  },
  professional: {
    experience: '6 years full-time',
    specialties: ['Senior dogs', 'Reactive dogs', 'Group walks'],
    breeds: ['All breeds', 'Puppies', 'Large breeds'],
    languages: ['English', 'Spanish'],
    certifications: ['Canine CPR', 'Pet First Aid', 'Fear-Free'],
    maxDogs: 4,
    transport: 'Car available for pickups',
  },
  recentServices: [
    {
      id: 'service_1',
      time: 'Yesterday',
      pets: 3,
      type: 'Dog walking',
      location: 'Williamsburg',
      description: 'Walk with 2 dogs and 1 cat check-in. Hydration logged, report shared.',
      rating: 4.9,
      status: 'completed',
    },
    {
      id: 'service_2',
      time: '2 days ago',
      pets: 1,
      type: 'Home visit',
      location: 'Park Slope',
      description: 'Feeding, medication given, litter cleaned. Photo report sent.',
      rating: 5,
      status: 'completed',
    },
    {
      id: 'service_3',
      time: '3 days ago',
      pets: 2,
      type: 'Pet sitting',
      location: 'DUMBO',
      description: 'Full-day sitting, both dogs walked and fed. Health check completed.',
      rating: 4.8,
      status: 'completed',
    },
  ],
  reviews: [
    {
      id: 'review_1',
      author: 'Amanda S.',
      text: 'Always so thorough and sends detailed notes.',
      rating: 5,
      helpful: 12,
    },
    {
      id: 'review_2',
      author: 'Mark T.',
      text: 'Handled my anxious rescue with patience.',
      rating: 4.8,
      helpful: 8,
    },
  ],
  companies: [
    {
      name: 'North Lake Vet',
      rating: 4.9,
      role: 'Veterinary Partner',
    },
    {
      name: 'PawWalks Seattle',
      rating: 4.8,
      role: 'Dog Walking',
    },
    {
      name: 'Happy Critters',
      rating: 4.6,
      role: 'Pet Sitting',
    },
  ],
  media: {
    photos: [],
    gpsSnapshots: [],
    healthReports: [],
  },
  booking: {
    nextAvailable: 'Today, 2:30 PM',
    defaultPrice30min: 28,
    currency: 'USD',
  },
};
