import type { ComponentType } from 'react';
import type { LucideProps } from 'lucide-react';
import {
  Activity,
  ArrowLeft,
  Award,
  Bird,
  Briefcase,
  Calendar,
  Car,
  CheckCircle,
  ChevronDown,
  CircleCheck,
  CirclePlus,
  CircleX,
  Clock,
  Clock3,
  Clock4,
  CreditCard,
  Footprints,
  Globe,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Images,
  Info,
  MapPin,
  MessageCircle,
  PawPrint,
  Pencil,
  Phone,
  Plus,
  Repeat,
  ScanFace,
  Scissors,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Star,
  Sun,
  ThumbsUp,
  Timer,
  TrendingUp,
  TriangleAlert,
  Users,
} from 'lucide-react';

import type { AllowedIconName } from '@/shared/icons/allowedIcons';
import { cn } from '@/shared/utils/cn';

const ICONS: Record<AllowedIconName, ComponentType<LucideProps>> = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  award: Award,
  bird: Bird,
  briefcase: Briefcase,
  calendar: Calendar,
  car: Car,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'circle-check': CircleCheck,
  'circle-plus': CirclePlus,
  'circle-x': CircleX,
  clock: Clock,
  'clock-3': Clock3,
  'clock-4': Clock4,
  'credit-card': CreditCard,
  footprints: Footprints,
  globe: Globe,
  headphones: Headphones,
  heart: Heart,
  'heart-pulse': HeartPulse,
  house: House,
  images: Images,
  info: Info,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'paw-print': PawPrint,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  repeat: Repeat,
  'scan-face': ScanFace,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  star: Star,
  sun: Sun,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  users: Users,
};

type AppIconProps = LucideProps & {
  name: AllowedIconName;
  tone?: 'default' | 'accent' | 'success' | 'warning' | 'muted' | 'danger';
};

export const AppIcon = ({ name, tone = 'default', className, ...props }: AppIconProps) => {
  const Icon = ICONS[name];
  return <Icon className={cn('icon', `icon--${tone}`, className)} {...props} />;
};
